create table public.clinic_scraped_data (
  id bigserial not null,
  clinic_id uuid null,
  url text not null,
  name text null,
  slug text null,
  address text null,
  city text null,
  country text null,
  google_place_id text null,
  description text null,
  techniques text[] null,
  services text[] null,
  body_areas text[] null,
  languages_spoken text[] null,
  price_range_raw text null,
  price_per_graft_usd numeric null,
  price_min_usd numeric null,
  price_max_usd numeric null,
  currency_noted text null,
  financing_available boolean null default false,
  price_confidence text null,
  doctors jsonb null,
  certifications text[] null,
  memberships text[] null,
  accreditations text[] null,
  years_experience integer null,
  years_established integer null,
  cases_performed integer null,
  success_rate_pct numeric null,
  has_online_booking boolean null default false,
  offers_free_consultation boolean null default false,
  offers_virtual_consultation boolean null default false,
  booking_url text null,
  has_before_after boolean null default false,
  data_quality text null,
  scraped_at timestamp with time zone null,
  cleaned_at timestamp with time zone null,
  pages_scraped integer null,
  scrape_ok boolean null default false,
  error text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  constraint clinic_scraped_data_pkey primary key (id),
  constraint clinic_scraped_data_url_key unique (url),
  constraint clinic_scraped_data_clinic_id_fkey foreign key (clinic_id) references clinics (id) on delete cascade
) tablespace pg_default;

create trigger set_updated_at before
update on clinic_scraped_data for each row
execute function update_updated_at_column();